# Triage_HF Statistical & Graphical Analytical Model
* Started date: 02/07/2024 - 05:09 AM
* Data Management team, Triage_HF

# 1. Dataset cleaning
We will import our dataset and perform a first cleanup to begin to understand which columns and values we are dealing with.

In [14]:
import numpy as np
import pandas as pd
import plotly.express as px

pd.set_option('display.max.rows', None)
pd.set_option('display.max.columns', None)

In [15]:
train_df = pd.read_csv('../dataset/raw/TRIAGE 2024.csv')

In [16]:
train_df.head()

,3+-99999|a,[ñ_MJ,NOMBRE Y APELLIDO,MOTIVO DE CONSULTA,BOX,TRIAGE,ENFERMERO,MEDICO,DESTINO,A,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,FECHA: 01/01/2024 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,01-01,LUSI,FIEBRE Y TOS,18,IV,ERIKA,RODRIGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,01-01,LO PINTO CARLOS,FIEBRE Y TOS,17,IV,SOLEDAD G,SOLEDAD,alta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,01-01,BANDERA,TOS,12,IV,ERIKA,RODRIGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,01-01,TOMINO EDUARDO,HTA,12,IV,SOLEDAD G,SOLEDAD,ALTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

At first, you can see how certain columns are wrongly named, so I will assign a corresponding name to them:

In [17]:
cols_rename = { '[ñ_MJ': 'FECHA DE INGRESO',
                'A': 'AISLADO' }
train_df.rename(columns = cols_rename, inplace = True)

In addition, each time you move to the next day according to the date of entry, the first column returns to 1:

In [18]:
train_df.loc[train_df['FECHA DE INGRESO'] == '01-01', '3+-99999|a'].iloc[0] == train_df.loc[train_df['FECHA DE INGRESO'] == '01-02', '3+-99999|a'].iloc[0]

True

Therefore, I will name that first column "NUMERO DE TURNO" in reference to the fact that the turns are reset at the beginning of the next day:

In [19]:
col_rename = { '3+-99999|a': 'NUMERO DE TURNO' }
train_df.rename(columns = col_rename, inplace = True)

We will remove the header that appears every time a new day begins:

In [20]:
train_df = train_df[train_df['NUMERO DE TURNO'].str.contains('FECHA') == False]

For possible machine learning models in the future, the triage level should be int dtype:

In [21]:
vals_rename = { 'I': 1, 'II': 2, 'III': 3, 'IV': 4 }
train_df['TRIAGE'] = train_df['TRIAGE'].replace(vals_rename)

In [22]:
train_df['TRIAGE'].dtype

dtype('O')

However, for the moment we will leave it in object type because it has missing values, and then we will decide what to do with them:

In [23]:
train_df['TRIAGE'].isnull().count()

1634

Finally, empty and unnamed columns can be visualized. We will remove them:

In [24]:
cols_to_keep = ['NUMERO DE TURNO', 'FECHA DE INGRESO', 'NOMBRE Y APELLIDO', 'MOTIVO DE CONSULTA', 'BOX', 'TRIAGE', 'ENFERMERO', 'MEDICO', 'DESTINO', 'AISLADO']
train_df = train_df[cols_to_keep]

This is how our dataframe would look at first:

In [27]:
train_df.head()

,NUMERO DE TURNO,FECHA DE INGRESO,NOMBRE Y APELLIDO,MOTIVO DE CONSULTA,BOX,TRIAGE,ENFERMERO,MEDICO,DESTINO,AISLADO
1,1,01-01,LUSI,FIEBRE Y TOS,18,4,ERIKA,RODRIGO,NaN,NaN
2,2,01-01,LO PINTO CARLOS,FIEBRE Y TOS,17,4,SOLEDAD G,SOLEDAD,alta,NaN
3,3,01-01,BANDERA,TOS,12,4,ERIKA,RODRIGO,NaN,NaN
4,4,01-01,TOMINO EDUARDO,HTA,12,4,SOLEDAD G,SOLEDAD,ALTA,NaN
5,5,01-01,D IORIO ROLANDO EMILIO,FIEBRE,5,4,ERIKA,SOLEDAD,NaN,NaN

In [39]:
def turnos_fecha(desde, hasta):
    train_df_acotado = train_df[train_df['FECHA DE INGRESO'] != np.nan]
    train_df_acotado = pd.to_datetime(train_df_acotado['FECHA DE INGRESO'], format='%d-%m', errors='coerce')
    print(train_df_acotado)
    #train_df_acotado = train_df_acotado[(train_df_acotado['FECHA DE INGRESO'] >= desde) & (train_df_acotado['FECHA DE INGRESO'] <= hasta)]
    #cantidad_pacientes = train_df_acotado.groupby('FECHA DE INGRESO')['NUMERO DE TURNO'].count().reset_index()
    #print(cantidad_pacientes)
    #fig = px.bar(cantidad_pacientes, x='FECHA DE INGRESO', y='NUMERO DE TURNO', barmode="group")
    #fig.show()
    
turnos_fecha("01-01", "02-01")

1      1900-01-01
2      1900-01-01
3      1900-01-01
4      1900-01-01
5      1900-01-01
6      1900-01-01
7      1900-01-01
8      1900-01-01
9      1900-01-01
10     1900-01-01
11     1900-01-01
12     1900-01-01
13     1900-01-01
14     1900-01-01
15     1900-01-01
16     1900-01-01
17     1900-01-01
18     1900-01-01
20     1900-01-02
21     1900-01-02
22     1900-01-02
23     1900-01-02
24     1900-01-02
25     1900-01-02
26     1900-01-02
27     1900-01-02
28     1900-01-02
29     1900-01-02
30     1900-01-02
31     1900-01-02
32     1900-01-02
33     1900-01-02
34     1900-01-02
35     1900-01-02
36     1900-01-02
37     1900-01-02
38     1900-01-02
39     1900-01-02
40     1900-01-02
41     1900-01-02
42     1900-01-02
43     1900-01-02
44     1900-01-02
45     1900-01-02
46     1900-01-02
47     1900-01-02
48     1900-01-02
49     1900-01-02
50     1900-01-02
51     1900-01-02
52     1900-01-02
53     1900-01-02
54     1900-01-02
55     1900-01-02
56     1900-01-02
57     1900-01-02
58     1900-01-02
59     1900-01-02
60     1900-01-02
61     1900-01-02
62     1900-01-02
63     1900-01-02
64     1900-01-02
65     1900-01-02
66     1900-01-02
67     1900-01-02
68     1900-01-02
69     1900-01-02
70     1900-01-02
71     1900-01-02
72     1900-01-02
74     1900-01-03
75     1900-01-03
76     1900-01-03
77     1900-01-03
78     1900-01-03
79     1900-01-03
80     1900-01-03
81     1900-01-03
82     1900-01-03
83     1900-01-03
84     1900-01-03
85     1900-01-03
86     1900-01-03
87     1900-01-03
88     1900-01-03
89     1900-01-03
90     1900-01-03
91     1900-01-03
92     1900-01-03
93     1900-01-03
94     1900-01-03
95     1900-01-03
96     1900-01-03
97     1900-01-03
98     1900-01-03
99     1900-01-03
100    1900-01-03
101    1900-01-03
102    1900-01-03
103    1900-01-03
104    1900-01-03
105    1900-01-03
106    1900-01-03
107    1900-01-03
108    1900-01-03
109    1900-01-03
110    1900-01-03
111    1900-01-03
112    1900-01-03
113    1900-01-03
114    1900-01-03
115    1900-01-03
116    1900-01-03
117    1900-01-03
119    1900-01-04
120    1900-01-04
121    1900-01-04
122    1900-01-04
123    1900-01-04
124    1900-01-04
125    1900-01-04
126    1900-01-04
127    1900-01-04
128    1900-01-04
129    1900-01-04
130    1900-01-04
131    1900-01-04
132    1900-01-04
133    1900-01-04
134    1900-01-04
135    1900-01-04
136    1900-01-04
137    1900-01-04
138    1900-01-04
139    1900-01-04
140    1900-01-04
141    1900-01-04
142    1900-01-04
143    1900-01-04
144    1900-01-04
145    1900-01-04
146    1900-01-04
147    1900-01-04
148    1900-01-04
149    1900-01-04
150    1900-01-04
151    1900-01-04
152    1900-01-04
153    1900-01-04
154    1900-01-04
155    1900-01-04
156    1900-01-04
157    1900-01-04
158    1900-01-04
160    1900-01-05
161    1900-01-05
162    1900-01-05
163    1900-01-05
164    1900-01-05
165    1900-01-05
166    1900-01-05
167    1900-01-05
168    1900-01-05
169    1900-01-05
170    1900-01-05
171    1900-01-05
172    1900-01-05
173    1900-01-05
174    1900-01-05
175    1900-01-05
176    1900-01-05
177    1900-01-05
178    1900-01-05
179    1900-01-05
180    1900-01-05
181    1900-01-05
182    1900-01-05
183    1900-01-05
184    1900-01-05
185    1900-01-05
186    1900-01-05
187    1900-01-05
188    1900-01-05
189    1900-01-05
190    1900-01-05
191    1900-01-05
192    1900-01-05
193    1900-01-05
194    1900-01-05
195    1900-01-05
196    1900-01-05
197    1900-01-05
198    1900-01-05
199    1900-01-05
201    1900-01-06
202    1900-01-06
203    1900-01-06
204    1900-01-06
205    1900-01-06
206    1900-01-06
207    1900-01-06
208    1900-01-06
209    1900-01-06
210    1900-01-06
211    1900-01-06
212    1900-01-06
213    1900-01-06
214    1900-01-06
215    1900-01-06
216    1900-01-06
217    1900-01-06
218    1900-01-06
219    1900-01-06
220    1900-01-06
221    1900-01-06
222    1900-01-06
223    1900-01-06
224    1900-01-06
225    1900-01-06
226    1900-01-06
227    1900-01-06
229    1900-01-06
230    1900-01-06
232    1900-01-07
233    1900-01-07
234    1900-01-07
235    1900-01-07
236    1900-01-07
237    1900-01-07
238    1900-01-07
239    1900-01-07
240    1900-01-07
241    1900-01-07
242    1900-01-07
243    1900-01-07
244    1900-01-07
245    1900-01-07
246    1900-01-07
247    1900-01-07
249    1900-01-08
250    1900-01-08
251    1900-01-08
252    1900-01-08
253    1900-01-08
254    1900-01-08
255    1900-01-08
256    1900-01-08
257    1900-01-08
258    1900-01-08
259    1900-01-08
260    1900-01-08
261    1900-01-08
262    1900-01-08
263    1900-01-08
264    1900-01-08
265    1900-01-08
266    1900-01-08
267    1900-01-08
268    1900-01-08
269    1900-01-08
270    1900-01-08
271    1900-01-08
272    1900-01-08
273    1900-01-08
274    1900-01-08
275    1900-01-08
276    1900-01-08
277    1900-01-08
278    1900-01-08
279    1900-01-08
280    1900-01-08
281    1900-01-08
282    1900-01-08
283    1900-01-08
284    1900-01-08
285    1900-01-08
286    1900-01-08
287    1900-01-08
288    1900-01-08
289    1900-01-08
290    1900-01-08
291    1900-01-08
292    1900-01-08
293    1900-01-08
294    1900-01-08
295    1900-01-08
296    1900-01-08
297    1900-01-08
298    1900-01-08
299    1900-01-08
300    1900-01-08
301    1900-01-08
302    1900-01-08
303    1900-01-08
304    1900-01-08
305    1900-01-08
306    1900-01-08
307    1900-01-08
308    1900-01-08
310    1900-01-09
311    1900-01-09
312    1900-01-09
313    1900-01-09
314    1900-01-09
315    1900-01-09
316    1900-01-09
317    1900-01-09
318    1900-01-09
319    1900-01-09
320    1900-01-09
321    1900-01-09
322    1900-01-09
323    1900-01-09
324    1900-01-09
325    1900-01-09
326    1900-01-09
327    1900-01-09
328    1900-01-09
329    1900-01-09
330    1900-01-09
331    1900-01-09
332    1900-01-09
333    1900-01-09
334    1900-01-09
335    1900-01-09
336    1900-01-09
337    1900-01-09
338    1900-01-09
339    1900-01-09
340    1900-01-09
341    1900-01-09
342    1900-01-09
343    1900-01-09
344    1900-01-09
345    1900-01-09
346    1900-01-09
347    1900-01-09
348    1900-01-09
349    1900-01-09
350    1900-01-09
351    1900-01-09
352    1900-01-09
353    1900-01-09
354    1900-01-09
355    1900-01-09
356    1900-01-09
357    1900-01-09
359    1900-01-10
360    1900-01-10
361    1900-01-10
362    1900-01-10
363    1900-01-10
364    1900-01-10
365    1900-01-10
366    1900-01-10
367    1900-01-10
368    1900-01-10
369    1900-01-10
370    1900-01-10
371    1900-01-10
372    1900-01-10
373    1900-01-10
374    1900-01-10
375    1900-01-10
376    1900-01-10
377    1900-01-10
378    1900-01-10
379    1900-01-10
380    1900-01-10
381    1900-01-10
382    1900-01-10
383    1900-01-10
384    1900-01-10
385    1900-01-10
386    1900-01-10
387    1900-01-10
388    1900-01-10
389    1900-01-10
390    1900-01-10
391    1900-01-10
392    1900-01-10
393    1900-01-10
394    1900-01-10
395    1900-01-10
396    1900-01-10
397    1900-01-10
398    1900-01-10
399    1900-01-10
400    1900-01-10
401    1900-01-10
402    1900-01-10
403    1900-01-10
404    1900-01-10
405    1900-01-10
406    1900-01-10
407    1900-01-10
408    1900-01-10
409    1900-01-10
411    1900-01-11
412    1900-01-11
413    1900-01-11
414    1900-01-11
415    1900-01-11
416    1900-01-11
417    1900-01-11
418    1900-01-11
419    1900-01-11
420    1900-01-11
421    1900-01-11
422    1900-01-11
423    1900-01-11
424    1900-01-11
425    1900-01-11
426    1900-01-11
427    1900-01-11
428    1900-01-11
429    1900-01-11
430    1900-01-11
431    1900-01-11
432    1900-01-11
433    1900-01-11
434    1900-01-11
435    1900-01-11
436    1900-01-11
437    1900-01-11
438    1900-01-11
439    1900-01-11
440    1900-01-11
441    1900-01-11
442    1900-01-11
443    1900-01-11
444    1900-01-11
445    1900-01-11
446    1900-01-11
447    1900-01-11
449    1900-01-12
450    1900-01-12
451    1900-01-12
452    1900-01-12
453    1900-01-12
454    1900-01-12
455    1900-01-12
456    1900-01-12
457    1900-01-12
458    1900-01-12
459    1900-01-12
460    1900-01-12
461    1900-01-12
462    1900-01-12
463    1900-01-12
464    1900-01-12
465    1900-01-12
466    1900-01-12
467    1900-01-12
468    1900-01-12
469    1900-01-12
470    1900-01-12
471    1900-01-12
472    1900-01-12
473    1900-01-12
474    1900-01-12
475    1900-01-12
476    1900-01-12
477    1900-01-12
478    1900-01-12
479    1900-01-12
480    1900-01-12
481    1900-01-12
482    1900-01-12
483    1900-01-12
485    1900-01-13
486    1900-01-13
487    1900-01-13
488    1900-01-13
489    1900-01-13
490    1900-01-13
491    1900-01-13
492    1900-01-13
493    1900-01-13
494    1900-01-13
495    1900-01-13
496    1900-01-13
497    1900-01-13
498    1900-01-13
499    1900-01-13
500    1900-01-13
501    1900-01-13
502    1900-01-13
503    1900-01-13
504    1900-01-13
505    1900-01-13
506    1900-01-13
507    1900-01-13
508    1900-01-13
509    1900-01-13
510    1900-01-13
511    1900-01-13
512    1900-01-13
514    1900-01-14
515    1900-01-14
516    1900-01-14
517    1900-01-14
518    1900-01-14
519    1900-01-14
520    1900-01-14
521    1900-01-14
522    1900-01-14
523    1900-01-14
524    1900-01-14
525    1900-01-14
526    1900-01-14
527    1900-01-14
528    1900-01-14
529    1900-01-14
530    1900-01-14
531    1900-01-14
532    1900-01-14
533    1900-01-14
535    1900-01-15
536    1900-01-15
537    1900-01-15
538    1900-01-15
539    1900-01-15
540    1900-01-15
541    1900-01-15
542    1900-01-15
543    1900-01-15
544    1900-01-15
545    1900-01-15
546    1900-01-15
547    1900-01-15
548    1900-01-15
549    1900-01-15
550    1900-01-15
551    1900-01-15
552    1900-01-15
553    1900-01-15
554    1900-01-15
555    1900-01-15
556    1900-01-15
557    1900-01-15
558    1900-01-15
559    1900-01-15
560    1900-01-15
561    1900-01-15
562    1900-01-15
563    1900-01-15
564    1900-01-15
565    1900-01-15
566    1900-01-15
567    1900-01-15
568    1900-01-15
569    1900-01-15
570    1900-01-15
571    1900-01-15
572    1900-01-15
573    1900-01-15
574    1900-01-15
575    1900-01-15
576    1900-01-15
577    1900-01-15
579    1900-01-16
580    1900-01-16
581    1900-01-16
582    1900-01-16
583    1900-01-16
584    1900-01-16
585    1900-01-16
586    1900-01-16
587    1900-01-16
588    1900-01-16
589    1900-01-16
590    1900-01-16
591    1900-01-16
592    1900-01-16
593    1900-01-16
594    1900-01-16
595    1900-01-16
596    1900-01-16
597    1900-01-16
598    1900-01-16
599    1900-01-16
600    1900-01-16
601    1900-01-16
602    1900-01-16
603    1900-01-16
604    1900-01-16
605    1900-01-16
606    1900-01-16
607    1900-01-16
608    1900-01-16
609    1900-01-16
610    1900-01-16
611    1900-01-16
612    1900-01-16
614    1900-01-17
615    1900-01-17
616    1900-01-17
617    1900-01-17
618    1900-01-17
619    1900-01-17
620    1900-01-17
621    1900-01-17
622    1900-01-17
623    1900-01-17
624    1900-01-17
625    1900-01-17
626    1900-01-17
627    1900-01-17
628    1900-01-17
629    1900-01-17
630    1900-01-17
631    1900-01-17
632    1900-01-17
633    1900-01-17
634    1900-01-17
635    1900-01-17
636    1900-01-17
637    1900-01-17
638    1900-01-17
639    1900-01-17
640    1900-01-17
641    1900-01-17
642    1900-01-17
643    1900-01-17
644    1900-01-17
645    1900-01-17
646    1900-01-17
647    1900-01-17
648    1900-01-17
649    1900-01-17
650    1900-01-17
651    1900-01-17
652    1900-01-17
653    1900-01-17
654    1900-01-17
655    1900-01-17
656    1900-01-17
657    1900-01-17
658    1900-01-17
659    1900-01-17
660    1900-01-17
662    1900-01-18
663    1900-01-18
664    1900-01-18
665    1900-01-18
666    1900-01-18
667    1900-01-18
668    1900-01-18
669    1900-01-18
670    1900-01-18
671    1900-01-18
672    1900-01-18
673    1900-01-18
674    1900-01-18
675    1900-01-18
676    1900-01-18
677    1900-01-18
678    1900-01-18
679    1900-01-18
680    1900-01-18
681    1900-01-18
682    1900-01-18
683    1900-01-18
684    1900-01-18
685    1900-01-18
686    1900-01-18
687    1900-01-18
688    1900-01-18
689    1900-01-18
690    1900-01-18
691    1900-01-18
692    1900-01-18
693    1900-01-18
694    1900-01-18
695    1900-01-18
696    1900-01-18
697    1900-01-18
698    1900-01-18
699    1900-01-18
700    1900-01-18
701    1900-01-18
703    1900-01-19
704    1900-01-19
705    1900-01-19
706    1900-01-19
707    1900-01-19
708    1900-01-19
709    1900-01-19
710    1900-01-19
711    1900-01-19
712    1900-01-19
713    1900-01-19
714    1900-01-19
715    1900-01-19
716    1900-01-19
717    1900-01-19
718    1900-01-19
719    1900-01-19
720    1900-01-19
721    1900-01-19
722    1900-01-19
723    1900-01-19
724    1900-01-19
725    1900-01-19
726    1900-01-19
727    1900-01-19
728    1900-01-19
729    1900-01-19
730    1900-01-19
731    1900-01-19
732    1900-01-19
733    1900-01-19
734    1900-01-19
735    1900-01-19
736    1900-01-19
737    1900-01-19
738    1900-01-19
739    1900-01-19
740    1900-01-19
741    1900-01-19
742    1900-01-19
743    1900-01-19
744    1900-01-19
745    1900-01-19
746    1900-01-19
747    1900-01-19
748    1900-01-19
749    1900-01-19
751    1900-01-20
752    1900-01-20
753    1900-01-20
754    1900-01-20
755    1900-01-20
756    1900-01-20
757    1900-01-20
758    1900-01-20
759    1900-01-20
760    1900-01-20
761    1900-01-20
762    1900-01-20
763    1900-01-20
764    1900-01-20
765    1900-01-20
766    1900-01-20
767    1900-01-20
768    1900-01-20
769    1900-01-20
770    1900-01-20
771    1900-01-20
772    1900-01-20
773    1900-01-20
774    1900-01-20
775    1900-01-20
776    1900-01-20
777    1900-01-20
779    1900-01-21
780    1900-01-21
781    1900-01-21
782    1900-01-21
783    1900-01-21
784    1900-01-21
785    1900-01-21
786    1900-01-21
787    1900-01-21
788    1900-01-21
789    1900-01-21
790    1900-01-21
791    1900-01-21
792    1900-01-21
793    1900-01-21
794    1900-01-21
795    1900-01-21
796    1900-01-21
797    1900-01-21
799    1900-01-22
800    1900-01-22
801    1900-01-22
802    1900-01-22
803    1900-01-22
804    1900-01-22
805    1900-01-22
806    1900-01-22
807    1900-01-22
808    1900-01-22
809    1900-01-22
810    1900-01-22
811    1900-01-22
812    1900-01-22
813    1900-01-22
814    1900-01-22
815    1900-01-22
816    1900-01-22
817    1900-01-22
818    1900-01-22
819    1900-01-22
820    1900-01-22
821    1900-01-22
822    1900-01-22
823    1900-01-22
824    1900-01-22
825    1900-01-22
826    1900-01-22
827    1900-01-22
828    1900-01-22
829    1900-01-22
830    1900-01-22
831    1900-01-22
832    1900-01-22
833    1900-01-22
834    1900-01-22
835    1900-01-22
836    1900-01-22
837    1900-01-22
838    1900-01-22
839    1900-01-22
840    1900-01-22
841    1900-01-22
842    1900-01-22
843    1900-01-22
844    1900-01-22
845    1900-01-22
846    1900-01-22
847    1900-01-22
848    1900-01-22
849    1900-01-22
850    1900-01-22
851    1900-01-22
852    1900-01-22
853    1900-01-22
854    1900-01-22
855    1900-01-22
856    1900-01-22
857    1900-01-22
858    1900-01-22
859    1900-01-22
860    1900-01-22
861    1900-01-22
862    1900-01-22
864    1900-01-13
865    1900-01-23
866    1900-01-23
867    1900-01-23
868    1900-01-23
869    1900-01-23
870    1900-01-23
871    1900-01-23
872    1900-01-23
873    1900-01-23
874    1900-01-23
875    1900-01-23
876    1900-01-23
877    1900-01-23
878    1900-01-23
879    1900-01-23
880    1900-01-23
881    1900-01-23
882    1900-01-23
883    1900-01-23
884    1900-01-23
885    1900-01-23
886    1900-01-23
887    1900-01-23
888    1900-01-23
889    1900-01-23
890    1900-01-23
891    1900-01-23
892    1900-01-23
893    1900-01-23
894    1900-01-23
895    1900-01-23
896    1900-01-23
897    1900-01-23
898    1900-01-23
899    1900-01-23
900    1900-01-23
901    1900-01-23
902    1900-01-23
903    1900-01-23
904    1900-01-23
905    1900-01-23
906    1900-01-23
907    1900-01-23
909    1900-01-24
910    1900-01-24
911    1900-01-24
912    1900-01-24
913    1900-01-24
914    1900-01-24
915    1900-01-24
916    1900-01-24
917    1900-01-24
918    1900-01-24
919    1900-01-24
920    1900-01-24
921    1900-01-24
922    1900-01-24
923    1900-01-24
924    1900-01-24
925    1900-01-24
926    1900-01-24
927    1900-01-24
928    1900-01-24
929    1900-01-24
930    1900-01-24
931    1900-01-24
932    1900-01-24
933           NaT
935    1900-01-25
936    1900-01-25
937    1900-01-25
938    1900-01-25
939    1900-01-25
940    1900-01-25
941    1900-01-25
942    1900-01-25
943    1900-01-25
944    1900-01-25
945    1900-01-25
946    1900-01-25
947    1900-01-25
948    1900-01-25
949    1900-01-25
950    1900-01-25
951    1900-01-25
952    1900-01-25
953    1900-01-25
954    1900-01-25
955    1900-01-25
956    1900-01-25
957    1900-01-25
958    1900-01-25
959    1900-01-25
960    1900-01-25
961    1900-01-25
962    1900-01-25
963    1900-01-25
964    1900-01-25
965    1900-01-25
966    1900-01-25
967    1900-01-25
968    1900-01-25
969    1900-01-25
970    1900-01-25
971    1900-01-25
972    1900-01-26
973    1900-01-26
974    1900-01-26
975    1900-01-26
976    1900-01-26
977    1900-01-26
978    1900-01-26
979    1900-01-26
980    1900-01-26
981    1900-01-26
982    1900-01-26
983    1900-01-26
984    1900-01-26
985    1900-01-26
986    1900-01-26
987    1900-01-26
988    1900-01-26
989    1900-01-26
990    1900-01-26
991    1900-01-26
992    1900-01-26
993    1900-01-26
994    1900-01-26
995    1900-01-26
996    1900-01-26
997    1900-01-26
998    1900-01-26
999    1900-01-26
1000   1900-01-26
1001   1900-01-26
1002   1900-01-26
1003   1900-01-26
1004   1900-01-26
1005   1900-01-26
1007   1900-01-26
1008   1900-01-26
1009   1900-01-26
1010   1900-01-26
1011   1900-01-26
1012   1900-01-26
1013   1900-01-26
1014   1900-01-26
1015   1900-01-26
1016   1900-01-26
1017   1900-01-26
1019   1900-01-27
1020   1900-01-27
1021   1900-01-27
1022   1900-01-27
1023   1900-01-27
1024   1900-01-27
1025   1900-01-27
1026   1900-01-27
1027   1900-01-27
1028   1900-01-27
1029   1900-01-27
1030   1900-01-27
1031   1900-01-27
1032   1900-01-27
1033   1900-01-27
1034   1900-01-27
1035   1900-01-27
1036   1900-01-27
1037   1900-01-27
1038   1900-01-27
1039   1900-01-27
1040   1900-01-27
1042   1900-01-28
1043   1900-01-28
1044   1900-01-28
1045   1900-01-28
1046   1900-01-28
1047   1900-01-28
1048   1900-01-28
1049   1900-01-28
1050   1900-01-28
1051   1900-01-28
1052   1900-01-28
1053   1900-01-28
1054   1900-01-28
1055   1900-01-28
1056   1900-01-28
1057   1900-01-28
1059   1900-01-29
1060   1900-01-29
1061   1900-01-29
1062   1900-01-29
1063   1900-01-29
1064   1900-01-29
1065   1900-01-29
1066   1900-01-29
1067   1900-01-29
1068   1900-01-29
1069   1900-01-29
1070   1900-01-29
1071   1900-01-29
1072   1900-01-29
1073   1900-01-29
1074   1900-01-29
1075   1900-01-29
1076   1900-01-29
1077   1900-01-29
1078   1900-01-29
1079   1900-01-29
1080   1900-01-29
1081   1900-01-29
1082   1900-01-29
1083   1900-01-29
1084   1900-01-29
1085   1900-01-29
1086   1900-01-29
1087   1900-01-29
1088   1900-01-29
1089   1900-01-29
1090   1900-01-29
1091   1900-01-29
1092   1900-01-29
1093   1900-01-29
1094   1900-01-29
1095   1900-01-29
1096   1900-01-29
1097   1900-01-29
1098   1900-01-29
1099   1900-01-29
1100   1900-01-29
1101   1900-01-29
1102   1900-01-29
1104   1900-01-30
1105   1900-01-30
1106   1900-01-30
1107   1900-01-30
1108   1900-01-30
1109   1900-01-30
1110   1900-01-30
1111   1900-01-30
1112   1900-01-30
1113   1900-01-30
1114   1900-01-30
1115   1900-01-30
1116   1900-01-30
1117   1900-01-30
1118   1900-01-30
1119   1900-01-30
1120   1900-01-30
1122   1900-01-30
1123   1900-01-30
1124   1900-01-30
1125   1900-01-30
1126   1900-01-30
1127   1900-01-30
1128   1900-01-30
1129   1900-01-30
1130   1900-01-30
1131   1900-01-30
1132   1900-01-30
1133   1900-01-30
1145   1900-01-31
1146   1900-01-31
1147   1900-01-31
1148   1900-01-31
1149   1900-01-31
1150   1900-01-31
1151   1900-01-31
1152   1900-01-31
1153   1900-01-31

In [32]:
print(train_df.loc[24])

NUMERO DE TURNO                       5
FECHA DE INGRESO                  02-01
NOMBRE Y APELLIDO     RIPAMONTI GUSTAVO
MOTIVO DE CONSULTA       DOLOR DE PECHO
BOX                                  17
TRIAGE                                2
ENFERMERO                        SILVIA
MEDICO                          MARTIN
DESTINO                             NaN
AISLADO                              NO
Name: 24, dtype: object