# Triage_HF Statistical & Graphical Analytical Model
* Started date: 02/07/2024 - 05:09 AM
* Data Management Team, Triage_HF

# 1. Dataset cleaning
We will import our dataset and perform a first cleanup to begin to understand which columns and values we are dealing with.

In [191]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import datetime as dt
import plotly.io as pio


import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
import string

import gensim
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


#pio.renderers.default = "browser"
pd.options.mode.chained_assignment = None
pd.set_option('display.max.rows', None)
pd.set_option('display.max.columns', None)

There are two ways to import our data set:
1. Locally: if we have the repository locally, we will use the following line

In [192]:
# Locally method
train_df = pd.read_csv('../dataset/raw/TRIAGE_2024.csv')

2. Remotely: if we want to connect the dataset from github, we must import it using the following line


**WARNING**: every time we want to use this form, we must generate the token again.

In [193]:
# Github method
# train_df = pd.read_csv('https://raw.githubusercontent.com/Adriellevy/Triage_HF/main/Data%20Analysis%20and%20Reports/dataset/raw/TRIAGE%202024.csv?token=GHSAT0AAAAAACLM5VZGUTNJJPTGADJMMUKEZOQ3JLA')

In [194]:
train_df.head()

,3+-99999|a,[ñ_MJ,NOMBRE Y APELLIDO,MOTIVO DE CONSULTA,BOX,TRIAGE,ENFERMERO,MEDICO,DESTINO,A,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,FECHA: 01/01/2024 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,01-01,LUSI,FIEBRE Y TOS,18,IV,ERIKA,RODRIGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,01-01,LO PINTO CARLOS,FIEBRE Y TOS,17,IV,SOLEDAD G,SOLEDAD,alta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,01-01,BANDERA,TOS,12,IV,ERIKA,RODRIGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,01-01,TOMINO EDUARDO,HTA,12,IV,SOLEDAD G,SOLEDAD,ALTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1.1 Columns rename

At first, you can see how certain columns are wrongly named, so I will assign a corresponding name to them:

In [195]:
cols_rename = { '[ñ_MJ': 'FECHA DE INGRESO',
                'A': 'AISLADO' }
train_df.rename(columns = cols_rename, inplace = True)

In addition, each time you move to the next day according to the date of entry, the first column returns to 1:

In [196]:
train_df.loc[train_df['FECHA DE INGRESO'] == '01-01', '3+-99999|a'].iloc[0] == train_df.loc[train_df['FECHA DE INGRESO'] == '01-02', '3+-99999|a'].iloc[0]

True

Therefore, I will name that first column "NUMERO DE TURNO" in reference to the fact that the turns are reset at the beginning of the next day:

In [197]:
col_rename = { '3+-99999|a': 'NUMERO DE TURNO' }
train_df.rename(columns = col_rename, inplace = True)

## 1.2 Removing headers and null rows

We will remove the header that appears every time a new day begins:

In [198]:
train_df = train_df[train_df['NUMERO DE TURNO'].str.contains('FECHA|N°') == False]

In addition, we will remove the last rows of the dataset that do not contain any value in first and last name

In [199]:
train_df = train_df[train_df['NOMBRE Y APELLIDO'].notnull()]

## 1.3 Changing Triage Level data type

For possible machine learning models in the future, the triage level should be int dtype:

In [200]:
train_df['TRIAGE'].dtype

dtype('O')

In [201]:
train_df['TRIAGE'] = train_df['TRIAGE'].str.strip().str.upper()

In [202]:
vals_rename = { 'I': 1, 'II': 2, 'III': 3, 'IV': 4 }
train_df['TRIAGE'] = train_df['TRIAGE'].replace(vals_rename)

Those rows not containing 1, 2, 3, or 4 will be taken as null (using errors coerce)

In [203]:
train_df['TRIAGE'] = pd.to_numeric(train_df['TRIAGE'], downcast = "signed", errors = 'coerce')

In [204]:
train_df['TRIAGE'].dtype

dtype('float64')

## 1.4 Changing Entry Date data type

We will change the object type of the entry date to date type. This makes date manipulation much easier and more readable:

In [205]:
train_df['FECHA DE INGRESO'].dtype

dtype('O')

In [206]:
train_df['FECHA DE INGRESO'] = train_df['FECHA DE INGRESO'] + '-2024'

In [207]:
train_df['FECHA DE INGRESO'] = pd.to_datetime(train_df['FECHA DE INGRESO'], format = '%d-%m-%Y', errors = 'coerce')

In [208]:
train_df['FECHA DE INGRESO'].dtype

dtype('<M8[ns]')

## 1.5 Changing Isolated data type

In [209]:
train_df['AISLADO'].unique()

array([nan, 'KPC', 'NO', 'SI', 'No', '724', 'Si', 'ECOLI METALO'],
      dtype=object)

In [210]:
data = {'AISLADO': [np.nan, 'KPC', 'NO', 'SI', 'No', '724', 'Si', 'A', 'ECOLI METALO']}
mapping = {np.nan: False, 'NO': False, 'No': False,
           'KPC': True, 'ECOLI METALO': True, 'SI': True, 'Si': True, 'A': True}
train_df['AISLADO'] = train_df['AISLADO'].map(mapping)

In [211]:
train_df = train_df[train_df['AISLADO'] != '724']

In [212]:
train_df['AISLADO'] = train_df['AISLADO'].astype(bool)

## 1.6 Generating ALTA column

In [213]:
train_df['DESTINO'].unique()

array([nan, 'alta', 'ALTA', '624', 'ALTA ', 'FUGA', '506', '?', 'INT',
       '715', '721', '512', '717', '820', '622', 'ALT.VOL', '312', '812',
       'HMD/ 315', 'HMD', '316', '301', '806', 'Alta', '802', '809',
       'PISO', '315', '722', '805', 'alta ', 'OBITO', 'Traslado', ' ',
       '    ', '311', '808', 'ALTA VOLUNT', '302', '813', '818', '304',
       'ALTA V ', '814', '613', '619', '602', '615', 'ALTA MEDICA', '314',
       '626', '607', '726', 'ALTA VOL', '926', '922', '920', '917', '916',
       '711', 'DERIVACION', '714', '719', '  ', '724', 'FUGA ', 'DERIV',
       'AL. VOL', '915', '918', 'QUIROFANO', 'ALTA VOLUNT.', '310',
       'TRASLADO ', '928', '919', '616', 'QUIROFANO ', '628', '909',
       '804', 'ALTA VOLUNTARIA', 'DERIVACION ', '720', '803', 'DERIVAC',
       'alTA', '908', '709', '621', '306',
       'ALTA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '],
      dtype=object)

In [214]:
train_df = train_df[~train_df['DESTINO'].isin(['?', 'INT', 'HMD/ 315', 'HMD', ' ', '    ', '  ', ])]

In [215]:
train_df['ALTA'] = train_df['DESTINO'].str.contains(
    'alta|obito|traslado|derivacion|AL. VOL|DERIVAC',
    case=False,  
    regex=True   
)
train_df['ALTA'].fillna(True, inplace=True)

Finally, empty and unnamed columns can be visualized. We will remove them:

In [216]:
cols_to_keep = ['NUMERO DE TURNO', 'FECHA DE INGRESO', 'NOMBRE Y APELLIDO', 'MOTIVO DE CONSULTA', 'BOX', 'TRIAGE', 'ENFERMERO', 'MEDICO', 'DESTINO', 'ALTA', 'AISLADO']
train_df = train_df[cols_to_keep]

This is how our dataframe would look at first:

In [217]:
train_df.head()

,NUMERO DE TURNO,FECHA DE INGRESO,NOMBRE Y APELLIDO,MOTIVO DE CONSULTA,BOX,TRIAGE,ENFERMERO,MEDICO,DESTINO,ALTA,AISLADO
1,1,2024-01-01,LUSI,FIEBRE Y TOS,18,4.0,ERIKA,RODRIGO,NaN,True,False
2,2,2024-01-01,LO PINTO CARLOS,FIEBRE Y TOS,17,4.0,SOLEDAD G,SOLEDAD,alta,True,False
3,3,2024-01-01,BANDERA,TOS,12,4.0,ERIKA,RODRIGO,NaN,True,False
4,4,2024-01-01,TOMINO EDUARDO,HTA,12,4.0,SOLEDAD G,SOLEDAD,ALTA,True,False
5,5,2024-01-01,D IORIO ROLANDO EMILIO,FIEBRE,5,4.0,ERIKA,SOLEDAD,NaN,True,False

In [218]:
def grafico_barras(df, p_x, p_y, title, x_title, y_title, media = None):
    fig = px.bar(df, x=p_x, y=p_y, barmode="group")
    fig.update_layout(title=title, xaxis_title=x_title, yaxis_title=y_title, title_x=0.5)
    fig.update_traces(texttemplate='%{y}', textposition='outside')
    if(media):
        media = df[p_y].mean()
        fig.add_trace(go.Scatter(x=df[p_x],
                                 y=[media] * len(df),
                                 mode='lines',
                                 name='Media',
                                 line=dict(color='red', width=2, dash='dash'),
                                 hovertemplate='%{y:.2f}'))
        fig.add_annotation(
        xref='paper', yref='y',
        x=-0.03, y=media,
        text=f'{media:.2f}',
        showarrow=False,
        font=dict(color='red'))
    fig.show()

In [219]:
def filtros(df, desde = None, hasta = None, nombre_y_apellido = None, motivo_de_consulta = None, box = None, triage = None, medico = None, enfermero = None, alta = None, aislado = None):
    if(desde != None and hasta != None):
        desde = pd.to_datetime(desde, format='%d-%m-%Y', errors='coerce') 
        hasta = pd.to_datetime(hasta, format='%d-%m-%Y', errors='coerce')   
        df = df[(df['FECHA DE INGRESO'] >= desde) & (df['FECHA DE INGRESO'] <= hasta)]
        
    df['FECHA DE INGRESO'] = df['FECHA DE INGRESO'].dt.strftime('%d-%m-%Y')      
       
    if(nombre_y_apellido != None):
        df = df[df['NOMBRE Y APELLIDO'] == nombre_y_apellido]

    if(motivo_de_consulta != None):
        df = df[df['MOTIVO DE CONSULTA'] == motivo_de_consulta]

    if(box != None):
        df = df[df['BOX'] == box]

    if(triage != None):
        df = df[df['TRIAGE'] == triage]

    if(medico != None):
        df = df[df['MEDICO'] == medico]

    if(enfermero != None):
        df = df[df['ENFERMERO'] == enfermero]

    if(alta != None):
        df = df[df['ALTA'] == alta]

    if(aislado != None):
        df = df[df['AISLADO'] == aislado]

    return df

In [220]:
def cant_pacientes_fecha(desde = None, hasta = None, nombre_y_apellido = None, motivo_de_consulta = None, box = None, triage = None, medico = None, enfermero = None, alta = None, aislado = None):
    train_df_acotado = train_df.groupby('FECHA DE INGRESO', sort=False).size().reset_index()
    train_df_acotado.rename(columns={0: 'CANTIDAD DE PACIENTES'}, inplace=True)
    train_df_acotado = filtros(train_df_acotado, desde, hasta, nombre_y_apellido, motivo_de_consulta, box, triage, medico, enfermero, alta, aislado)
    return train_df_acotado

In [221]:
df = cant_pacientes_fecha(desde = None, hasta = None,
             nombre_y_apellido = None, motivo_de_consulta = None,
             box = None, triage = None,
             medico = None, enfermero = None,
             alta = None, aislado = None)

grafico_barras(df = df, 
               p_x='FECHA DE INGRESO', p_y='CANTIDAD DE PACIENTES', 
               x_title='Cantidad de Pacientes por Fecha de Ingreso', y_title='Fecha de Ingreso', title='Cantidad de Pacientes', 
               media=True)

In [222]:
def top_consultas_fecha(desde=None, hasta=None, top = 10, order=None, nombre_y_apellido = None, motivo_de_consulta = None, box = None, triage = None, medico = None, enfermero = None, alta = None, aislado = None):
    top_motivos = train_df.copy(deep=True)
    top_motivos = filtros(top_motivos, desde, hasta, nombre_y_apellido, motivo_de_consulta, box, triage, medico, enfermero, alta, aislado)
    
    motivos_count = top_motivos['MOTIVO DE CONSULTA'].value_counts()

    top_motivos = motivos_count.nlargest(top).reset_index()
    top_motivos.columns = ['MOTIVO DE CONSULTA', 'CANTIDAD DE CONSULTAS']

    if order == 'asc':
        top_motivos.sort_values(by='CANTIDAD DE CONSULTAS', ascending = True, inplace = True)
        
    return top_motivos

In [223]:
df = top_consultas_fecha(desde = None, hasta=None,
             top = 15, order = 'asc',
             nombre_y_apellido = None, motivo_de_consulta = None,
             box = None, triage = None,
             medico = None, enfermero = None,
             alta = None, aislado = None)

grafico_barras(df = df, 
               p_x='MOTIVO DE CONSULTA', p_y='CANTIDAD DE CONSULTAS', 
               title='Cantidad de Consultas', x_title='Motivos de Consulta mas Frecuentes', y_title='Motivo de Consulta', 
               media=False)

In [224]:
def cant_pacientes_triage(desde = None, hasta = None, nombre_y_apellido = None, motivo_de_consulta = None, box = None, triage = None, medico = None, enfermero = None, alta = None, aislado = None):
    train_df_acotado = train_df.groupby('TRIAGE', sort=False).size().reset_index()
    train_df_acotado.rename(columns={0: 'CANTIDAD DE PACIENTES'}, inplace=True)
    train_df_acotado = filtros(train_df_acotado, desde, hasta, nombre_y_apellido, motivo_de_consulta, box, triage, medico, enfermero, alta, aislado)
    return train_df_acotado

In [225]:
# df = cant_pacientes_triage(desde = None, hasta = None,
#              nombre_y_apellido = None, motivo_de_consulta = None,
#              box = None, triage = None,
#              medico = None, enfermero = None,
#              alta = None, aislado = None)

# grafico_barras(df = df, 
#                p_x='TRIAGE', p_y='CANTIDAD DE PACIENTES', 
#                x_title='Nivel de Triage', y_title='Cantidad de pacientes', title='Cantidad de Pacientes por Nivel de Triage', 
#                media=True)

In [226]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Adri\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Adri\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Adri\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [227]:
def preprocess_text(text):
    # convert to lowercase
    text = str(text).lower()

    # remove punctuation
    text = ''.join([char for char in text if char not in string.punctuation])

    # separate by syllables
    tokens = nltk.word_tokenize(text, 'spanish')

    # eliminate common words without meaning
    stop_words = set(stopwords.words('spanish'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatization (converting words to their base form)
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
    return ' '.join(lemmatized_tokens)

In [228]:
train_df['MOTIVO DE CONSULTA'] = train_df['MOTIVO DE CONSULTA'].apply(preprocess_text)

display(train_df['MOTIVO DE CONSULTA'])

1                              fiebre tos
2                              fiebre tos
3                                     tos
4                                     hta
5                                  fiebre
6                   sangrado bolsillo mcp
7                                 astenia
8                    hematuria hace 3 dia
9                                  fiebre
10                      dolor rodilla izq
11                           dolor lumbar
12           dolor hueco popliteo derecho
13                                diarrea
14                             odinofagia
15                                sincope
16                                sincope
17                              forunculo
18                       dolor costal izq
20                          palpitaciones
21                              hematuria
22                            dolor pecho
23                                    hta
24                            dolor pecho
25                          palpitaciones
26                                    tos
27                              dolor mid
28                                 disnea
29                                    hta
30                                     fa
31                            cervicalgia
32                              lumbalgia
33                                    itu
34                             edema mmii
35                    equimosis abdominal
36                             edema mmii
37                                 disnea
38                        gonalgiaomalgia
39                                disuria
40                                 hta dt
41                                    tvp
42                        consulta medica
43                      dolor pie derecho
44                          palpitaciones
45                                disuria
46                         dolor toraxico
47                                diarrea
48                                    tos
49                                 disnea
50                                astenia
51                            op tx renal
52                        consulta medica
53                        dolor abdominal
54                  dolor mid cervicalgia
55                             tos disnea
56                                    hta
57                              lumbalgia
58                                     ir
59                                diarrea
60                           hiperkalemia
61                                     dt
62
63                        dolor abdominal
64                      hta palpitaciones
65                     rinitis odinofagia
66                                    hta
67                         mareos cefalea
68                   palpitaciones disnea
69                            op tx renal
70                          palpitaciones
71                             choque cdi
72                              lumbalgia
74                             choque cdi
82                                 fiebre
83                        dolor abdominal
84                                     ir
85                                 mareos
86             cefalea tumoracion frontal
87                             odinofagia
88                            taquicardia
89                                ascitis
90                                    cva
91                          hta lumbalgia
92                                    hta
93                                   name
94                                    cva
95                   tx renal dolor pecho
96                         dolor inguinal
97               desplazamiento cable trc
98                           tx mo fiebre
99                  hematoma bolsillo cdi
100                       dolor abdominal
101                         palpitaciones
102                      palpitaciones dt
103                                    dt
104                          desaturacion
105                               diarrea
106                     odinofagia doidos
107                              cultivos
108                                    dt
109                       dolor abdominal
110                alteracion laboratorio
111                               cefalea
112                    cefalea cong nasal
113                       consulta medica
114                             lumbalgia
115                             lipotimia
116                       dolor abdominal
117                                anuria
119                                    dt
120                                   hta
121                             dolor abd
122                             edema msi
123                     control herida cx
124                            herida mii
125                      reflujo gastrico
126                         palpitaciones
127                        control medico
128                        disnea astenia
129                           dolor pecho
130                                   hta
131                                 mreos
132                    lesion cutanea mii
133                      quiste abdominal
134                        control medico
135                                disnea
136                   herida cortante msd
137                                    dt
138                         dehidratacion
139                                   hta
140                       dolor abdominal
141                                    ic
142                           cefalea hta
143                       mordedura perro
144                               diarrea
145                                disnea
146                                disnea
147                                   iam
148                            odinofagia
149                           dolor pecho
150                                   hta
151                                   tvp
152                       dolor herida qx
153                               prurito
154                         palpitaciones
155                       dolor abdominal
156                         palpitaciones
157                                fiebre
158                               sincope
160                                disnea
161                      tx renal cefalea
162                               sincope
163                   tosasteniafebricula
164                                   cva
165                            odinofagia
166          dehiscencia herida abdominal
167                            edema mmii
168                               cefalea
169                               astenia
170                             edema mii
171                       control estudio
172                               diarrea
173                               astenia
174                             dolor abd
175                         palpitaciones
176                               vomitos
177                               ascitis
178                       quiste temporal
180                            edema mmii
182                           dolor pecho
183                       dolor abdominal
184                       dolor abdominal
185                sangrado sitio puncion
186                       espasmo vesical
187                             edema mii
188                         epigastralgia
189                       vomitos diarrea
190                 dolor parrilla costal
191                               rinitis
192                             cv fiebre
193                    hemiparecia facial
194                       dolro abdominal
195                         epigastralgia
196                                   nan
197                             dolor mii
198                            dt cefalea
199                          rush cutanea
201                             lipotimia
202                        dolor inguinal
203                                    dt
204                         palpitaciones
205                             hematuria
206                     control herida cx
207                 dolor espalda x caida
208                            odinofagia
209                      caida propia alt
210                      dolor epigastrio
211                                    dt
212                                    dt
213                         palpitaciones
214                                fiebre
215                                    dt
216                       dolor abdominal
217                         palpitaciones
218                                    dt
219         evaluacion estudio ecodoppler
220                                mareos
221                                   nan
222                            sme gripal
223                       dolor abdominal
224                           op tx renal
225                             lipotimia
226                            odinofagia
227                         palpitaciones
229                            fiebre cva
230                            fiebre cva
232                       dolor herida qx
233                             edema msd
234                                    dt
235                            odinofagia
236                               vomitos
237              fiebre 2 dia eritema pie
238                 disnea tos procuctiva
239                       dolor abdominal
240                                disnea
241                                fiebre
242                     dolor mmii fiebre
243               ruptura cateter broviak
244                               disuria
245            dolor punzante pie derecho
246                         palpitaciones
247                                   hta
249                       dolor abdominal
250                suboclusion intestinal
251                                fiebre
252                            odinofagia
253                  cva erupcion cutanea
254                                melena
255                                   nan
256                                disnea
257                    asteniahipotension
258                         palpitaciones
259                   trauma mano derecha
260            inflacion dolor testicular
261                      dolor abdominial
262                            odinofagia
263                             dolor fid
264                                    dt
265                   hta consulta medica
266                          desaturacion
267               dolor abdominal diarrea
268                       consulta medica
269                  mareos palpitaciones
270                           inflamacion
271                           internacion
272                   hipotension vomitos
273              tx renal dolor abdominal
274                                disnea
275                          dolor dorsal
276                       dolor abdominal
277                           lesion piel
278                     omalgia izquierda
279                     dolor meñique izq
280                hiporexiadisnea cf iii
281                      disuria post atb
282                       omalgia derecha
283                          pancreatitis
284                   dolor mmii tx renal
285                            odinofagia
286                                    ic
287                             disnea dt
288                  palpitaciones mareos
289                        tos edema mmii
290                               diarrea
291                       consulta medica
292                                disnea
293                                    dt
294                          isquemia mii
295                               disuria
296                            odinofagia
297                    hta dolor cervical
298                  dolor interescapular
299             desplazamiento stent esof
300                       dolor abdominal
301                            edema mmii
302                               alergia
303                                    dt
304                         palpitaciones
305                 consulta cardiologica
306                         palpitaciones
307                               cefalea
308                        dolor inguinal
310        mareos dolor abdominal vomitos
311                                   cva
312                             forunculo
313                          recambio cdi
314                                disnea
315                         temblor manos
316                           cva cefalea
317                              insomnio
318                        dolor toracico
319                desplazamiento cateter
320                        dolor toracico
321                               cefalea
322                                fiebre
323                     diseccion aortica
324               lesion morderuda canina
325                                   hta
326                 molestia bolsillo mcp
327                                   hta
328                                disnea
329                        debilidad mmii
330                                   cva
331                         epigastralgia
332                                mareos
333                                   nan
334                                   hta
335                      micosis pulmonar
337                                   hta
338                            disnea tos
339                                    dt
340                                    dt
341                           tos rinitis
342                             dolor mii
343                         edema eritema
344                               astenia
345                          desaturacion
346                                   hta
347                               vomitos
348                               disuria
349                        parecia facial
350                               astenia
351                  masa palpable cuello
352                                   nan
353                         epigastralgia
354               dolor adbominal vomitos
355                             lipotimia
356                     tos expectoracion
357                         palpitaciones
359                         palpitaciones
360                                fiebre
361                 dolor abdominaldorsal
362                             hematuria
363                          proctorragia
364                               vertigo
365                            dolor mmii
366                            dolor mmii
367                         fiebrecefalea
368               epigastralgiadiaforesis
369                     edema pie derecho
370              dolor inguinal izquierdo
371                                   tec
372              hematoma parrilla costal
373                            astenia dt
374                     dermatitis axilar
375                           estomatitis
376                                disnea
377                    consulta herida qx
378                  dolor mama izquierda
379                       amaurosis fugaz
380                               disuria
381                               sincope
382                                   hta
383                                mareos
384                             dolor msd
386                     parestesia facial
387                                    dt
388                               astenia
389                                disnea
391                       consulta medica
392                               disuria
393                                fiebre
394                          inest marcha
395                                   tos
396                              cultivos
397                              dist abd
398                                   nan
399              desplazamiento cable cdi
400                      congestion nasal
401                                   nan
402                        deshidratacion
403                            eco estres
404                                mareos
405                               cefalea
406                        debilidad mmii
407                        dolor toracico
408                          hematoquesia
409                        dolor toracico
411                          dolor dorsal
412                         palpitaciones
413                            odinofagia
414                        dolor toracico
415                                   sca
416                      erupcion cutanea
417                             epistaxis
418                               sincope
419                             epistaxis
420                             tosfiebre
421                       consulta medica
422                               diarrea
423                               disuria
424                             hematuria
425                         palpitaciones
426                               cefalea
427                                disnea
428                             lumbalgia
429                               astenia
430                      sangre mat fecal
431                    curacion herida qx
432                               vomitos
433                        dolor toracico
434                                    dt
435                            sme febril
436                                    dt
437                                 edema
438                         litisis renal
439                                   tos
440                     control herida qx
441                               astenia
442                             hematuria
443                         epigastralgia
444                                    dt
445                                fiebre
446                 hemiparesia izquierda
447                                    dt
449                            fiebre irc
450                                   cva
451                               disuria
452                       dolor abdominal
453                         palpitaciones
454                                fiebre
455                            edema mmii
456                           sincope tec
457                         palpitaciones
458                                mareos
459                             febricula
460                             temblores
461                      tx renal astenia
462                         cefaleafiebre
463                       parestesias msi
464                     dolor intercostal
465                             dt disnea
466               dolor abdominal diarrea
467                             dolor abd
468                             dolor abd
469                             lumbalgia
470                             lumbalgia
471                  control bolsillo cdi
472                dolor hombro izquierdo
473                        sme febril tos
474                            odinofagia
475                     dolor intercostal
476                               reflujo
477                    cultivos positivos
478                                   nan
479                                otitis
480                                   hta
481                                   hta
482                                    dt
485                                    ic
486                             lumbalgia
487                    shock cardiogenico
488                        dolor inguinal
489                         palpitaciones
490                        dolor inguinal
491                        dolor toracico
492                       tx renal fiebre
493                    mareos tx cardiaco
494                       dolor abdominal
495                             dolor mii
496                 hematoma mano derecha
497                           op tx renal
498                                    dt
499                               cefalea
500                                   tos
501                                    dt
502                 lesion partes blandas
503                            tos mareos

In [229]:
# sintomas_rellenados_por_enfermeros = [sentence.split() for sentence in train_df['MOTIVO DE CONSULTA']]


# # Cargar el modelo preentrenado
# model = KeyedVectors.load_word2vec_format('..\dataset\Pre-Trained-Word2Vec-Files\GoogleNews-vectors-negative300.bin', binary=True)

# # Ahora puedes usar el modelo para encontrar los síntomas más similares
# sintomas_no_entrenados=[]
# for lista_sintomas in sintomas_rellenados_por_enfermeros:
#     print(f"Lista de síntomas: {lista_sintomas}")
#     # Para cada síntoma en la lista...
#     for sintoma in lista_sintomas:
#         print(f"  Síntoma: {sintoma}")
#         # Verificar si el síntoma está en el vocabulario del modelo
#         if sintoma in model.key_to_index:
#             # Encontrar el síntoma más similar
#             similares = model.most_similar(sintoma, topn=1)
#             for sim in similares:
#                 print(f"    Síntoma más similar: {sim[0]} (similitud: {sim[1]})")
#         else:
#             sintomas_no_entrenados.append(sintoma)
#             #print(f"    El síntoma '{sintoma}' no está en el vocabulario del modelo.")

In [243]:
sintomas_rellenados_por_enfermeros = [sentence.split() for sentence in train_df['MOTIVO DE CONSULTA']]
#print(sintomas_rellenados_por_enfermeros)
#Entreno el modelo usando los sintomas ideales (esto puede variari no solo por cada centro sino por temporada)
#Agegue a la lista que nos pasaron el sintoma tos, habría que evaluar otros posibles casos de eso
sintomas_ideales=[['convulsiones'],
    ['trauma de cráneo'],
    ['dolor torácico'],
    ['dorsal'],
    ['dolor abdominal'],
    ['lumbar'],
    ['cefalea'],
    ['déficit motor'],
    ['disartria'],
    ['afasia'],
    ['pérdida aguda de visión'],
    ['disnea'],
    ['otro dolor en curso'],
    ['sobredosis de fármacos'],
    ['ingesta de tóxicos'],
    ['sangrado digestivo'],
    ['fiebre'],
    ['tos']]
corpus = sintomas_ideales + sintomas_rellenados_por_enfermeros
model = KeyedVectors.load('..\dataset\Pre-Trained-Word2Vec-Files\complete.kv', mmap='r')


sintoma_mas_similar = ''
mayor_similitud = -1

# SintomaIngresado = sintomas_rellenados_por_enfermeros[0][0]
SintomaIngresado = "fiebre "
#if SintomaIngresado in model.wv.key_to_index:
for sintoma_ideal in sintomas_ideales:
    sintoma_ideal = sintoma_ideal[0]
    if sintoma_ideal in model.wv.key_to_index:
        similitud = model.wv.similarity(SintomaIngresado, sintoma_ideal)
    if similitud > mayor_similitud:
        mayor_similitud = similitud
        sintoma_mas_similar = sintoma_ideal
print(f"El síntoma ideal más similar a '{SintomaIngresado}' es '{sintoma_mas_similar}' con una similitud de {mayor_similitud}.")
#else:
 #   print("El síntoma ingresado no está en el vocabulario del modelo.")


# sintomas_no_entrenados=[]
# for lista_sintomas in sintomas_rellenados_por_enfermeros:
#     print(f"Lista de síntomas: {lista_sintomas}")
#     Para cada síntoma en la lista...
#     for sintoma in lista_sintomas:
#         print(f"  Síntoma: {sintoma}")
#         Verificar si el síntoma está en el vocabulario del modelo
#         if sintoma in model.wv.key_to_index:
#             Encontrar el síntoma más similar
#             similares = model.wv.most_similar(sintoma, topn=1)
#             for sim in similares:
#                 print(f"    Síntoma más similar: {sim[0]} (similitud: {sim[1]})")
#         else:
#             sintomas_no_entrenados.append(sintoma)
#             print(f"    El síntoma '{sintoma}' no está en el vocabulario del modelo.")

TypeError: KeyedVectors.load_word2vec_format() got an unexpected keyword argument 'mmap'

In [231]:

# #Le asigno un valor a cada palabra
# for sintoma in sintomas_rellenados_por_enfermeros:
#     print(f"Síntoma: {sintoma}")
#     similares = model.wv.most_similar(sintoma)
#     for sim in similares:
#         print(f"  - {sim[0]}: {sim[1]}")


# sintomas_rellenados_por_enfermeros = train_df['MOTIVO DE CONSULTA'].tolist()
# #print(sintomas_rellenados_por_enfermeros)
# #Entreno el modelo usando los sintomas ideales (esto puede variari no solo por cada centro sino por temporada)
# #Agegue a la lista que nos pasaron el sintoma tos, habría que evaluar otros posibles casos de eso
# sintomas_ideales=[['convulsiones'],
#     ['trauma de cráneo'],
#     ['dolor torácico'], 
#     ['dorsal'],
#     ['dolor abdominal'], 
#     ['lumbar'],
#     ['cefalea'],
#     ['déficit motor'], 
#     ['disartria'], 
#     ['afasia'],
#     ['pérdida aguda de visión'],
#     ['disnea'],
#     ['otro dolor en curso'],
#     ['sobredosis de fármacos'],
#     ['ingesta de tóxicos'],
#     ['sangrado digestivo'],
#     ['fiebre'],
#     ['tos']]
# model = Word2Vec(sintomas_ideales, vector_size=50, window=5, min_count=1, sg=0)
# # #Le asigno un valor a cada palabra
# # for sintoma in sintomas_rellenados_por_enfermeros:
# #     print(f"Síntoma: {sintoma}")
# #     similares = model.wv.most_similar(sintoma)
# #     for sim in similares:
# #         print(f"  - {sim[0]}: {sim[1]}")

# sintomas_no_relacionados=[]
# for sintoma in sintomas_rellenados_por_enfermeros:
#     # Para cada síntoma en la lista...
#     print(f"  Síntoma: {sintoma}")
#     # Verificar si el síntoma está en el vocabulario del modelo
#     if sintoma in model.wv.key_to_index:
#     # Encontrar el síntoma más similar
#         similares = model.wv.most_similar(sintoma, topn=1)
#         for sim in similares:
#             print(f"    Síntoma más similar: {sim[0]} (similitud: {sim[1]})")
#     else:
#         sintomas_no_relacionados.append(sintoma)
#             #print(f"    El síntoma '{sintoma}' no está en el vocabulario del modelo.")

In [232]:
print("Cantidad de pacientes: " + str(train_df.shape[0]))
df = top_consultas_fecha(desde = "1-1-2024", hasta="3-3-2024",
             top = 50, order = 'asc',
             nombre_y_apellido = None, motivo_de_consulta = None,
             box = None, triage = None,
             medico = None, enfermero = None,
             alta = None, aislado = None)

grafico_barras(df = df, 
               p_x='MOTIVO DE CONSULTA', p_y='CANTIDAD DE CONSULTAS', 
               title='Cantidad de Consultas', x_title='Motivos de Consulta mas Frecuentes', y_title='Motivo de Consulta', 
               media=False)

Cantidad de pacientes: 1425

In [233]:
word_vectors = [model.wv[word] for word in model.wv.index_to_key]
print(word_vectors)
X = np.array(word_vectors)

kmeans = KMeans(n_clusters=13)
kmeans.fit(X)

cluster_labels = kmeans.labels_
word_clusters = {word: label for word, label in zip(model.wv.index_to_key, cluster_labels)}

for word, label in word_clusters.items():
    print(f"{word}: Clúster {label}")

[array([ 7.11202483e-06,  9.33861247e-06,  1.18259825e-02,  1.78940371e-02,
       -1.94028877e-02, -1.60645638e-02,  1.42518226e-02,  1.96973849e-02,
       -1.33454595e-02, -9.60635114e-03,  1.58169344e-02, -5.68908406e-03,
       -7.83389993e-03,  1.35560166e-02, -1.13432445e-02, -2.99686729e-03,
        6.73306547e-03,  2.83405650e-03, -1.95729118e-02, -2.11099610e-02,
        1.70080680e-02,  1.27611253e-02,  1.51219210e-02, -5.36428357e-04,
        1.39836641e-02, -6.89244317e-03, -3.83593817e-03,  1.04032429e-02,
       -1.77806187e-02, -7.67366309e-03, -1.62775125e-02, -7.10208900e-04,
        1.75320711e-02, -1.62956044e-02, -5.59876440e-03, -4.01723525e-03,
        1.81091335e-02, -1.10493768e-02,  6.12873817e-04, -1.21914567e-02,
       -1.93757173e-02,  8.33643321e-03, -1.60441492e-02, -8.42115749e-03,
        7.90549035e-04, -1.39184098e-03, -1.68559328e-02,  1.86278615e-02,
        1.06851459e-02,  1.93187334e-02], dtype=float32), array([-1.6079316e-02,  8.8495519e-03, -7.8449808e-03,  1.5458446e-03,
        1.6842965e-02, -9.4681606e-03,  9.2441635e-03, -1.3212853e-02,
       -7.8038564e-03,  1.8369772e-02, -3.0005304e-03, -3.5415360e-06,
       -7.9870252e-03, -1.5353145e-02, -3.3807573e-03,  5.1090475e-03,
       -1.4152954e-03,  1.1254644e-02, -6.0498659e-03,  4.0364135e-03,
        1.1396744e-02,  1.7234791e-02, -2.4793588e-03, -1.8983895e-02,
        8.8461954e-03,  1.2202649e-03,  1.4387239e-02, -1.8504998e-03,
       -5.8102515e-03, -1.7469771e-02, -1.9098836e-03,  6.0224622e-03,
        1.0503500e-02,  1.3792503e-02, -1.1656202e-02,  3.7956790e-03,
        1.2507156e-02, -9.4913794e-03, -6.2561608e-03,  1.3044758e-02,
        3.3645651e-03,  1.6036920e-06,  7.2881221e-03,  4.7190150e-04,
        1.9538285e-02,  9.7709810e-03, -1.8140770e-02, -1.4367792e-02,
        1.9242783e-03,  1.2952578e-02], dtype=float32), array([-0.01719336,  0.00724778,  0.01044742,  0.01145766,  0.01489823,
       -0.01243105,  0.00231253,  0.01216573, -0.00580114, -0.01246046,
       -0.00075819, -0.01682772, -0.01115004,  0.01421899,  0.00663533,
        0.01448867,  0.01364709,  0.01512282, -0.0076802 , -0.00119365,
        0.00481281, -0.00900428,  0.0168857 , -0.01978935,  0.01359692,
        0.00585241, -0.00993868,  0.00871392, -0.00353971,  0.01338016,
        0.01988675, -0.00867696, -0.00126896, -0.01151446,  0.00767094,
        0.00558062,  0.01383407,  0.01227347,  0.01908383,  0.01845972,
        0.01574523, -0.01412321, -0.01821447, -0.0006413 , -0.00614887,
        0.01569706,  0.01185135, -0.00318031,  0.0030466 ,  0.00361271],
      dtype=float32), array([ 0.01568051, -0.01898459, -0.00032422,  0.00694655, -0.00195334,
        0.01661166,  0.01810128,  0.01321612, -0.00169478,  0.01528404,
       -0.01698293,  0.00620298, -0.00918421, -0.01012968,  0.00706039,
        0.01070651,  0.01558947, -0.01163022,  0.01465816,  0.01306889,
       -0.00726035, -0.01724688,  0.01094476,  0.01288403, -0.00144953,
       -0.01340827, -0.01435915, -0.00509501,  0.01011128, -0.00725643,
       -0.01877525,  0.00767529,  0.0096234 , -0.01295584,  0.00233721,
       -0.00411104,  0.00018504, -0.01976835,  0.00548196, -0.0096496 ,
        0.00215894, -0.00328917,  0.00448213, -0.01579186, -0.00537023,
        0.00528082,  0.01048084, -0.00474644, -0.0189695 ,  0.0090084 ],
      dtype=float32), array([ 0.00016513,  0.0062697 , -0.01360549, -0.00276901,  0.01540522,
        0.0145075 , -0.00741059,  0.00551228, -0.01683583,  0.01250852,
       -0.0093275 , -0.00658343,  0.01879412,  0.00169573,  0.01492137,
       -0.01221933,  0.01057349,  0.01971178, -0.01694575, -0.01030843,
       -0.01413532, -0.00963619, -0.00755222, -0.01710677,  0.01582271,
       -0.00957566,  0.01653968,  0.01047566, -0.01329618,  0.00805932,
        0.0110911 , -0.01464875, -0.01485037, -0.0048914 , -0.01732307,
       -0.003032  , -0.00084241,  0.00653989,  0.00278458, -0.00185153,
       -0.01109029,  0.00357065, -0.0016903 ,  0.01363553,  0.00808588,
        0.00887871,  0.00278309, -0.00560682, -0.00871265, -0.0020534 ],
      dtype=float32), array([ 2.9238996e-03, -5.2895932e-03, -1.4105883e-02, -1.5599508e-02,
       -1.8266005e-02, -1.1868040e-02, -3.6593799e-03, -8.6576398e-03,
       -1.2944617e-02, -7.4497364e-03,  8.6077088e-03, -7.4647777e-03,
        1.6774110e-02,  3.0676734e-03, -1.4492232e-02,  1.8877015e-02,
        1.5281766e-02,  1.0992122e-02, -1.3708410e-02,  1.1591381e-02,
        8.0239801e-03,  1.0384916e-02,  8.5191224e-03,  3.8716102e-03,
       -6.3257501e-03,  1.6720664e-02,  1.9176351e-02,  7.5693708e-03,
       -5.6618713e-03, -6.9344101e-06,  2.4563805e-03, -1.6886190e-02,
       -1.6445599e-02, -5.2127702e-04,  2.4498950e-03, -1.1501800e-02,
       -9.4543528e-03, -1.4709670e-02,  1.6705614e-02,  2.2440696e-04,
       -9.0220943e-03,  1.1333830e-02,  1.8379761e-02, -8.1707127e-03,
        1.5962856e-02,  1.0745859e-02,  1.1735539e-02,  9.9752413e-04,
        1.6405702e-02, -1.4033557e-02], dtype=float32), array([-0.01644589,  0.01842139, -0.00030404, -0.00413096,  0.00924667,
       -0.00835794,  0.00550371,  0.0139707 ,  0.01191751, -0.0151951 ,
        0.01877807,  0.00910275,  0.00788566, -0.01243177,  0.01683704,
       -0.00420101,  0.01765434, -0.01054373, -0.01642305,  0.01349769,
        0.00350813, -0.00424592,  0.01925687,  0.01881894, -0.01945434,
        0.00500379,  0.01217125,  0.00763737,  0.00385978,  0.00085033,
        0.00130969, -0.00752133, -0.01442178, -0.00443651,  0.00782357,
        0.01760664,  0.01866597, -0.01188675, -0.01874989,  0.01935124,
        0.00687651,  0.01016084,  0.01272332, -0.00563951,  0.0147877 ,
        0.00564873,  0.0056916 , -0.00481832, -0.0062002 , -0.00470562],
      dtype=float32), array([ 0.00886109, -0.00010131, -0.01837023, -0.01942967, -0.01264253,
       -0.00090828,  0.00433135,  0.0193352 ,  0.01005331, -0.00930382,
        0.0008821 ,  0.00911971,  0.01579195, -0.00226862,  0.00815422,
       -0.0113538 , -0.00108971,  0.01657522, -0.00559824, -0.01996281,
        0.01223279, -0.00703738, -0.00193866,  0.01921206, -0.00427567,
       -0.00931979, -0.01132259,  0.01364294, -0.01217514,  0.00430009,
       -0.01075401,  0.01275633,  0.00837227,  0.00457592, -0.00341253,
       -0.00545564,  0.01849239,  0.01059231, -0.00434129, -0.01962661,
       -0.01465124, -0.00264897, -0.00104343, -0.00491043,  0.0197715 ,
       -0.00123448,  0.01139295, -0.01521322, -0.00495752, -0.01088521],
      dtype=float32), array([-0.01406025,  0.00251029, -0.01414955, -0.00450166,  0.0073525 ,
        0.01151291,  0.00252123,  0.00441895, -0.0087211 ,  0.01424919,
       -0.01245226,  0.00893638, -0.01632989,  0.00399942, -0.01009425,
       -0.0084205 , -0.00609792,  0.0114057 ,  0.01124237, -0.01045619,
        0.00186856, -0.01670413,  0.01596868,  0.01834862, -0.00532229,
        0.00159403,  0.00123766,  0.01076692, -0.01750624,  0.0011897 ,
        0.01373985,  0.00465553,  0.00223251, -0.01907673,  0.01685991,
       -0.01256981, -0.00556399,  0.00712546, -0.00142533,  0.00250059,
        0.00352306, -0.01389676, -0.01925656,  0.01831126,  0.01254941,
       -0.01387216,  0.006603  ,  0.00036475,  0.00961732, -0.01409319],
      dtype=float32), array([ 0.00814951,  0.00859614,  0.02011267, -0.00898683, -0.00273857,
       -0.01478145, -0.01933283, -0.01802027, -0.00233448, -0.01317589,
        0.00980587, -0.01258668,  0.0051606 ,  0.00158386, -0.00692433,
       -0.00188947,  0.02006575,  0.01839651, -0.00922741,  0.01803044,
       -0.01100209,  0.01216138, -0.00605275,  0.00654824,  0.00616587,
        0.01376127, -0.00492374,  0.01741485,  0.01488797, -0.01903292,
       -0.01609485, -0.01515207,  0.00561384, -0.00576206, -0.01401415,
       -0.01639572,  0.01678316,  0.00406542, -0.01862565, -0.00985579,
        0.00626893, -0.00949073,  0.01083526, -0.0083806 ,  0.00531566,
       -0.01620927,  0.01228573,  0.00952685,  0.00170338,  0.00615785],
      dtype=float32), array([-0.01724176,  0.00431677, -0.00138051, -0.01865151, -0.0187874 ,
       -0.0034972 ,  0.00899198,  0.00774546, -0.01362145, -0.01425884,
       -0.00966274, -0.00529626, -0.01411265, -0.01927606, -0.00584091,
       -0.01680433, -0.01195008, -0.01103304, -0.00523992, -0.00374157,
       -0.01752005, -0.00091327,  0.01660396,  0.01504725, -0.01421721,
       -0.00737213,  0.00583915, -0.01944075,  0.00235466,  0.01310796,
        0.01155524, -0.01743281, -0.00942878, -0.01670924, -0.00015308,
        0.01867604,  0.01243884,  0.0102953 ,  0.01021458, -0.00708778,
        0.01915527, -0.01512434, -0.01408775, -0.00440157, -0.00136388,
       -0.00656372, -0.00152591,  0.01493492, -0.0013411 , -0.00324019],
      dtype=float32), array([ 5.7340288e-03, -1.6871242e-02,  1.6175138e-02,  1.6928034e-02,
       -1.9237937e-02,  4.3444247e-03,  1.9947113e-02, -1.5040471e-02,
       -1.4668531e-02, -1.5986092e-02,  1.7022876e-02, -2.0449576e-03,
        1.8609919e-02, -1.6227765e-02,  7.2491411e-03,  5.4556746e-03,
        1.6330300e-03,  4.9021649e-03, -1.5724678e-02, -1.9128563e-02,
        5.4394277e-03,  1.2989740e-02,  1.6422542e-02,  1.0930843e-02,
       -1.2624874e-03,  1.6535385e-02, -1.9059991e-02,  6.5059680e-03,
        4.5651250e-05,  7.8141484e-03,  1.4495425e-02, -1.3099575e-02,
        1.0972304e-02, -1.9455010e-02, -1.8713386e-03, -1.7427439e-02,
       -9.6423328e-03,  1.8826270e-02, -3.6871128e-03,  5.1965467e-03,
        1.8175911e-02,  1.7596545e-02, -1.6023867e-02, -6.0217059e-03,
        1.9960187e-02,  1.0075066e-02, -3.4250515e-03, -1.7483918e-02,
        6.0067605e-03, -1.3126312e-02], dtype=float32), array([ 0.01655819, -0.00910722, -0.00158292,  0.00187298, -0.00053697,
        0.00200706,  0.01258428,  0.00036585, -0.0070977 , -0.00335569,
        0.0120907 ,  0.00248188, -0.00119557,  0.01867393, -0.01016773,
       -0.0015487 ,  0.01857704,  0.01369524,  0.002547  , -0.01805134,
        0.00249203, -0.00407127,  0.01906741,  0.00187882,  0.00309585,
        0.00484019, -0.00409168, -0.01011974, -0.00011699, -0.00405562,
        0.01294965,  0.01820165, -0.00180397,  0.00554352, -0.01261429,
        0.00336948, -0.01361831, -0.01740132, -0.01173161, -0.01841632,
        0.01456529, -0.0120204 ,  0.01692832, -0.01455082,  0.00727712,
        0.01928832, -0.01573749, -0.02033381, -0.00863925, -0.00526258],
      dtype=float32), array([-0.00044739, -0.01768865, -0.01706255,  0.00554766, -0.01653786,
       -0.01837843, -0.00459584, -0.01703808, -0.01458981, -0.01704741,
       -0.00041042, -0.00944678,  0.01340268,  0.00303644, -0.00678438,
        0.01229544, -0.01182891, -0.00926821, -0.01469026, -0.0089751 ,
       -0.00337793,  0.01324519, -0.00535225,  0.00963021,  0.01385799,
       -0.0148705 ,  0.00879241,  0.01215771, -0.00618572,  0.01326413,
        0.01220866, -0.01261507, -0.01360536,  0.00489643, -0.00329205,
       -0.01206805,  0.01917707, -0.01015035, -0.01307052, -0.00053812,
       -0.00540602,  0.00072466, -0.00686671, -0.0007445 , -0.00130641,
        0.00151359,  0.01624875, -0.01164742, -0.0032586 ,  0.01123275],
      dtype=float32), array([ 1.72361396e-02, -8.74745287e-03,  1.89960524e-02,  1.69759262e-02,
       -9.58021171e-03, -7.26201106e-04,  9.40013491e-03, -7.09524285e-03,
       -1.30483285e-02, -1.43181961e-02, -6.99046941e-04, -1.77787908e-03,
        9.57191736e-03, -4.65243263e-03, -1.24991476e-03,  5.36103919e-03,
        1.08355209e-02,  8.26459436e-05, -1.41510339e-02, -1.98087413e-02,
        1.41446711e-03,  1.49483485e-02,  3.95212974e-03, -1.95097309e-02,
       -1.56718604e-02,  1.32706817e-02, -8.67375452e-03,  1.19385254e-02,
       -1.47996601e-02,  1.76952798e-02, -1.37682129e-02,  7.58390734e-03,
       -2.73255026e-03, -1.45788062e-02, -7.37453578e-03, -2.34674057e-03,
       -1.02527775e-02, -1.76795293e-03, -1.55675635e-02,  4.05660737e-03,
        1.83638129e-02, -6.01902790e-03, -1.33615069e-03,  7.69153284e-03,
        1.76137891e-02, -1.27049098e-02, -1.47113502e-02, -6.03331299e-03,
        1.85160786e-02,  2.30955146e-03], dtype=float32), array([-0.0173568 , -0.00289396,  0.01895893, -0.01509898, -0.0107162 ,
        0.01863313, -0.01794745,  0.00765182,  0.00133088,  0.0133214 ,
        0.01662551, -0.00570157, -0.00798463,  0.01779583,  0.00417929,
        0.01249788, -0.01889143,  0.01918025, -0.00269662, -0.01210423,
        0.00598507, -0.00091322,  0.00941299, -0.00456604, -0.00827568,
        0.0045558 ,  0.01670877, -0.00999121,  0.00533736, -0.01598111,
       -0.01354669, -0.00093534, -0.01753546,  0.00557888,  0.00319719,
       -0.00463938,  0.01000758,  0.01949757,  0.01690854, -0.00376045,
        0.0041163 , -0.00800738, -0.01648281,  0.01255591, -0.00389836,
       -0.00133241, -0.00354266, -0.00907133,  0.00812342, -0.00854036],
      dtype=float32), array([-1.9139128e-02,  1.7889515e-02,  8.4977075e-03,  1.8407701e-02,
        1.3320750e-02,  5.5550891e-03,  1.9547218e-02, -8.6448826e-03,
       -1.3964074e-02,  8.2298471e-03,  7.5174435e-03, -1.1660434e-02,
        1.9518388e-02, -7.0466883e-03,  1.8993421e-02,  1.7185828e-03,
       -1.2602883e-02, -3.9136875e-03, -1.4958302e-02, -6.0783769e-03,
        2.3257551e-03,  1.9186450e-02,  1.8854462e-02, -1.3415305e-02,
        7.0383400e-03,  4.5234570e-03, -5.1353341e-03, -1.8515484e-02,
        1.8153085e-03, -1.6260477e-02,  1.2566621e-02, -1.1487899e-02,
        1.0916886e-02,  1.9579804e-02, -4.3228667e-04,  9.0069994e-03,
       -3.4071405e-03,  1.4768190e-02,  7.9359422e-03, -1.8348169e-02,
       -4.7937408e-03,  7.0210341e-03, -6.9043075e-05, -2.3539381e-03,
       -2.0881235e-03, -3.5054637e-03,  9.8876213e-04,  8.3411084e-03,
       -8.4106559e-03, -7.6147509e-03], dtype=float32), array([ 5.23503877e-05,  4.84611664e-04, -1.47471103e-04, -9.50516574e-03,
        8.43615457e-03, -4.67637880e-03,  4.30646259e-03,  1.59381749e-03,
        1.14806267e-02, -1.39334416e-02, -1.34687545e-02, -9.43246298e-03,
        1.90873910e-02, -3.20880371e-03, -1.90716963e-02, -1.10781111e-03,
       -8.67776852e-03,  1.20741585e-02, -1.95188466e-02,  5.44370618e-03,
       -1.83158144e-02,  2.82242126e-03,  1.22687239e-02,  1.45857381e-02,
       -1.51071604e-02, -1.20255034e-02, -1.40557289e-02, -1.59214102e-02,
       -1.94551032e-02, -4.02430072e-03, -1.72027748e-03, -1.43654356e-02,
        1.34358089e-02,  2.03680503e-03,  1.15291243e-02,  2.99616996e-03,
        1.82112702e-03, -1.47212325e-02, -4.35720384e-03,  8.31637811e-03,
       -1.02136964e-02,  2.10767798e-03,  6.00478984e-03, -2.91499100e-03,
        2.00860035e-02,  1.65088251e-02,  4.58880980e-03,  1.40708508e-02,
        1.17960321e-02, -1.11384774e-02], dtype=float32), array([-0.01025259, -0.013315  , -0.01548198,  0.01669238, -0.00398667,
       -0.01373731, -0.00831775,  0.01033209, -0.00583965, -0.00754378,
        0.0033027 , -0.00563017, -0.00312143,  0.0021816 , -0.00600712,
        0.01705916,  0.00788256, -0.01994755,  0.0123896 , -0.01360368,
        0.0016016 ,  0.00891361, -0.01018455, -0.00428912,  0.0161859 ,
       -0.00846147, -0.01535629,  0.01853605, -0.00438333, -0.00934002,
        0.01710688,  0.00862894,  0.00863344,  0.01847657, -0.01693641,
        0.01051537,  0.00412347,  0.00841335,  0.00339619,  0.00883936,
        0.00897317,  0.01223593, -0.00640033, -0.00910288, -0.00076613,
        0.00501013, -0.00660855,  0.01205158,  0.00839906,  0.01555575],
      dtype=float32), array([ 0.00526856,  0.01607534, -0.00263461,  0.01618493,  0.00734958,
       -0.01636925, -0.00777465, -0.00488728,  0.00929903, -0.00204965,
       -0.00560536,  0.01534294,  0.01877517, -0.00315618, -0.01059119,
       -0.00931922, -0.00962695, -0.01907685,  0.00249263, -0.00868466,
        0.0053708 ,  0.01160777, -0.00795555, -0.0195589 ,  0.00319155,
       -0.01344813,  0.00471539, -0.00775063,  0.01387515,  0.00127772,
        0.00698144, -0.00528771, -0.00351722,  0.01505287,  0.00271401,
       -0.01182783, -0.01559028,  0.00259934,  0.01303792,  0.01084104,
       -0.01791572,  0.01706211,  0.00822448,  0.01506888,  0.01960598,
       -0.01474504, -0.01824447,  0.01164897,  0.0189733 ,  0.00696919],
      dtype=float32), array([ 0.01485967, -0.00323121,  0.01636604, -0.01896691, -0.01674792,
       -0.01457857, -0.00786632,  0.01082993, -0.0096948 , -0.01784801,
        0.01753121, -0.00867997,  0.01795917, -0.00973644,  0.00737952,
        0.01016687,  0.00574344, -0.00552503,  0.00434378, -0.01768182,
       -0.00463034, -0.00432199,  0.01534005, -0.00774108, -0.01329081,
        0.00882956, -0.00199444, -0.00787028,  0.01278376,  0.00814659,
       -0.00808624,  0.0023063 ,  0.01779036,  0.01506129,  0.01246082,
        0.00974556,  0.00594371, -0.00314725, -0.01290145, -0.00187117,
       -0.00312654, -0.00213302, -0.01224489,  0.01524624, -0.01293245,
       -0.01519068, -0.00615284, -0.00341045, -0.01539298,  0.00180395],
      dtype=float32), array([-1.06248213e-02, -2.52563064e-03, -1.46788973e-02,  3.95392999e-03,
        6.54684938e-03, -1.29057924e-04, -1.08152349e-02, -3.31931585e-03,
        1.40403351e-02,  7.43898470e-03, -1.77699197e-02, -6.96909847e-03,
        4.77890670e-03,  4.24600951e-03, -1.90418139e-02,  9.18133743e-03,
       -1.71924792e-02, -1.47444867e-02,  6.86405180e-03, -7.02967215e-03,
        7.23082852e-03,  1.79444011e-02, -7.12418836e-03,  1.85428411e-02,
        3.41495662e-03,  1.97011344e-02,  1.12944692e-02, -1.83715932e-02,
       -6.78194966e-03,  1.30292298e-02,  1.12389168e-02,  1.74908489e-02,
        1.38127115e-02,  1.60158016e-02, -1.97244901e-02,  8.54273979e-03,
       -9.94767249e-03,  7.01154955e-03,  1.21070901e-02,  8.72519333e-03,
        1.49999009e-02,  2.95830378e-03, -2.41754483e-03,  1.15988925e-02,
       -1.12268087e-02,  6.99613884e-05,  1.88537352e-02, -1.10142669e-02,
        7.69200642e-03, -1.61934868e-02], dtype=float32), array([ 1.9706735e-02,  1.6426051e-02,  2.6697868e-03,  1.0223656e-02,
        2.7989964e-03, -1.3141438e-02, -2.8813912e-03,  1.3262782e-02,
       -9.7955996e-03, -8.1390617e-03,  9.9816518e-03,  5.1123146e-03,
       -3.4649752e-03, -5.7253521e-03,  1.1758108e-02, -1.1450668e-02,
       -6.1162184e-03, -1.2996541e-02, -8.9127300e-03, -1.7460668e-02,
       -8.6617740e-03, -1.6575109e-02,  3.0190602e-03, -1.7598879e-02,
       -1.9797044e-02, -1.6194506e-02, -1.3949303e-02,  1.3276768e-02,
        7.1429512e-03,  9.2556258e-04, -5.8051529e-03, -1.4660479e-02,
        8.6410670e-04,  8.3871640e-04,  1.2338204e-04,  1.7517859e-03,
        1.7676366e-03, -4.6480483e-05, -1.6015835e-02, -1.2049591e-02,
       -1.6676044e-02, -2.7835120e-03,  3.7585692e-03,  1.5159086e-02,
       -3.8441555e-03, -4.9591628e-03,  1.8755358e-02, -1.8933484e-05,
       -4.7740256e-03,  1.7229144e-02], dtype=float32), array([ 0.00548929, -0.01075526,  0.01351888,  0.00889086, -0.01415051,
       -0.00107097,  0.00183921,  0.01181408, -0.003854  , -0.00593556,
        0.00372324,  0.0011577 ,  0.00263124, -0.00534031, -0.01231136,
        0.01465048,  0.01545688,  0.01673161, -0.01758249,  0.00493028,
       -0.00691753,  0.01960058,  0.00607435,  0.00899552,  0.00475765,
        0.01321923, -0.01191192,  0.01567449, -0.0053293 , -0.00915419,
       -0.00413041,  0.01970677, -0.01402316, -0.00462465,  0.01382809,
       -0.00011493, -0.01230281, -0.01283218,  0.01791284,  0.01249339,
        0.00960037, -0.0067862 , -0.01828493,  0.00760232,  0.01455591,
       -0.01147508, -0.01599558, -0.00614089, -0.00981823, -0.00468109],
      dtype=float32), array([-0.00386877, -0.01052638,  0.01910948, -0.01865242,  0.00898352,
        0.01069036, -0.00278143,  0.01833617,  0.01954233, -0.01115955,
       -0.01189841, -0.01375479, -0.01569712, -0.00613745, -0.0114469 ,
       -0.01668447,  0.00167276,  0.00602457,  0.01243083, -0.00555594,
       -0.00859133,  0.00278906,  0.00111483,  0.01599724,  0.00027639,
        0.01457387, -0.01662639,  0.01679731, -0.00419727,  0.01752321,

In [234]:
from sklearn.cluster import KMeans
import numpy as np

# Lista de síntomas
sintomas = [
    'Convulsiones',
    'Trauma de Cráneo',
    'Dolor torácico / dorsal',
    'Dolor abdominal / lumbar',
    'Cefalea',
    'Déficit motor',
    'Disartria - afasia',
    'Pérdida aguda de visión',
    'Disnea',
    'Otro dolor en curso',
    'Sobredosis de fármacos / Ingesta de tóxicos',
    'Sangrado Digestivo',
    'Fiebre >38°'
]

# Asumiendo que 'model' es un modelo Word2Vec entrenado
vectores_palabras = [model.wv[sintoma] for sintoma in sintomas if sintoma in model.wv]

# Verificar si la lista de vectores de palabras no está vacía
if vectores_palabras:
    X = np.array(vectores_palabras)

    # El número de clusters debe ser menor o igual al número de síntomas
    kmeans = KMeans(n_clusters=min(13, len(sintomas)))
    kmeans.fit(X)

    etiquetas_clusters = kmeans.labels_
    clusters_palabras = {sintoma: etiqueta for sintoma, etiqueta in zip(sintomas, etiquetas_clusters)}

    for sintoma, etiqueta in clusters_palabras.items():
        print(f"{sintoma}: Clúster {etiqueta}")
else:
    print("Ninguno de los síntomas está en el vocabulario del modelo Word2Vec.")

Ninguno de los síntomas está en el vocabulario del modelo Word2Vec.

In [235]:
#Usar pca para poder graficar y visualizar en dos dimensiones

# Use PCA to reduce the dimensionality of the word vectors to 2D
pca = PCA(n_components=2)
word_vectors_2d = pca.fit_transform(word_vectors)
# Create a DataFrame with the 2D word vectors and their corresponding words and cluster labels
df = pd.DataFrame(word_vectors_2d, columns=['Component 1', 'Component 2'])
df['Word'] = model.wv.index_to_key
df['Cluster Label'] = cluster_labels

# Create a scatter plot of the 2D word vectors, colored by their cluster labels, and with hover text for the words
fig = px.scatter(df, x='Component 1', y='Component 2', color='Cluster Label', hover_data=['Word'])
fig.show()

In [236]:
# Use PCA to reduce the dimensionality of the word vectors to 3D
pca = PCA(n_components=3)
word_vectors_3d = pca.fit_transform(word_vectors)

# Create a DataFrame with the 3D word vectors and their corresponding words and cluster labels
df = pd.DataFrame(word_vectors_3d, columns=['Component 1', 'Component 2', 'Component 3'])
df['Word'] = model.wv.index_to_key
df['Cluster Label'] = cluster_labels

# Create a 3D scatter plot of the word vectors, colored by their cluster labels, and with hover text for the words
fig = go.Figure(data=[go.Scatter3d(
    x=df['Component 1'],
    y=df['Component 2'],
    z=df['Component 3'],
    mode='markers',
    marker=dict(
        size=12,
        color=df['Cluster Label'],                # set color to an array/list of desired values
        colorscale='Viridis',   # choose a colorscale
        opacity=0.8
    ),
    text=df['Word']
)])

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig.show()